kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-00b27e7cb57d3c18d
    fsType: ext4
